server.port=8082
spring.application.name=fase4-payment-service

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.sqs.endpoint=https://sqs.us-east-1.amazonaws.com
# spring.cloud.aws.sqs.listener.execution-mode=blocking

# spring.config.import=aws-secretsmanager:fase4-payment-service-secrets

fase4.payment.service.marcadopago.webhookUrl=https://4f940ba021cb.ngrok-free.app/payment/webhook
fase4.payment.service.marcadopago.accessToken=APP_USR-6495398226501885-010600-2dfebee4f00b9fb3c7646c2b11d0350d-2331609065
fase4.payment.service.marcadopago.userID=2331609065
fase4.payment.service.marcadopago.externalPosID=FIAPSOATPOS